// Shared mock data for msfs-failures home screen variants.

window.FLEET = [
  {
    id: 'N172AB',
    tail: 'N172AB',
    type: 'C172',
    model: 'Cessna 172S Skyhawk',
    nickname: 'Old Faithful',
    status: 'airworthy',          // airworthy | squawks | grounded | mx-due
    hours: 1842.6,
    cycles: 2104,
    hobbsSinceMx: 24.3,
    nextInspectionHrs: 12.7,
    openSquawks: 0,
    deferred: 0,
    consumables: { oil: 0.78, tires: 0.62, brakes: 0.55, battery: 0.91, hyd: 0.99 },
    lastFlight: { date: '2026-04-29', dur: '1:42', maxG: 1.4, hardLandings: 0, overtemps: 0 },
    live: false,
  },
  {
    id: 'N812RP',
    tail: 'N812RP',
    type: 'PA-28',
    model: 'Piper PA-28-181 Archer III',
    nickname: 'Romeo Papa',
    status: 'squawks',
    hours: 3104.2,
    cycles: 4188,
    hobbsSinceMx: 47.1,
    nextInspectionHrs: 2.9,
    openSquawks: 2,
    deferred: 1,
    consumables: { oil: 0.41, tires: 0.34, brakes: 0.22, battery: 0.74, hyd: 0.88 },
    lastFlight: { date: '2026-04-30', dur: '0:58', maxG: 1.9, hardLandings: 1, overtemps: 1 },
    live: false,
  },
  {
    id: 'N350KA',
    tail: 'N350KA',
    type: 'BE350',
    model: 'Beechcraft King Air 350',
    nickname: 'The Beech',
    status: 'airworthy',
    hours: 5621.8,
    cycles: 3812,
    hobbsSinceMx: 8.4,
    nextInspectionHrs: 41.6,
    openSquawks: 1,
    deferred: 1,
    consumables: { oil: 0.66, tires: 0.71, brakes: 0.68, battery: 0.88, hyd: 0.94 },
    lastFlight: { date: '2026-04-30', dur: '2:14', maxG: 1.6, hardLandings: 0, overtemps: 0 },
    live: true,                   // ← currently loaded in sim
    liveState: {
      phase: 'CRUISE',
      altitude: 24000,
      ias: 218,
      gs: 252,
      hdg: 287,
      oat: -28,
      fuelKg: 1042,
      n1: [88.4, 88.1],
      itt: [712, 706],
      torque: [82, 81],
      oilTemp: [78, 76],
      oilPress: [82, 84],
      gear: 'UP',
      flaps: 0,
      hobbsStart: 5619.6,
      currentHobbs: 5621.8,
      session: { maxG: 1.6, overtemps: 0, hardLandings: 0, dur: '2:14' },
    },
  },
  {
    id: 'N58BS',
    tail: 'N58BS',
    type: 'BE58',
    model: 'Black Square Baron 58',
    nickname: 'Twin Sister',
    status: 'mx-due',
    hours: 2487.5,
    cycles: 2998,
    hobbsSinceMx: 99.2,
    nextInspectionHrs: 0.8,
    openSquawks: 1,
    deferred: 0,
    consumables: { oil: 0.31, tires: 0.48, brakes: 0.39, battery: 0.62, hyd: 0.71 },
    lastFlight: { date: '2026-04-28', dur: '1:18', maxG: 2.1, hardLandings: 0, overtemps: 2 },
    live: false,
  },
  {
    id: 'N210BS',
    tail: 'N210BS',
    type: 'C210',
    model: 'Black Square Cessna 210',
    nickname: 'The Centurion',
    status: 'grounded',
    hours: 4218.0,
    cycles: 3604,
    hobbsSinceMx: 4.2,
    nextInspectionHrs: 45.8,
    openSquawks: 3,
    deferred: 0,
    consumables: { oil: 0.52, tires: 0.18, brakes: 0.12, battery: 0.44, hyd: 0.88 },
    lastFlight: { date: '2026-04-22', dur: '0:34', maxG: 2.4, hardLandings: 1, overtemps: 0 },
    live: false,
  },
];

window.SQUAWKS = [
  {
    id: 'SQ-1042',
    tail: 'N812RP',
    component: '#2 Magneto',
    summary: 'Rough on runup, ~75 RPM drop on right mag, intermittent miss.',
    severity: 'open',          // open | deferred | grounding
    melDeferrable: true,
    opened: '2026-04-30',
    hoursAtOpen: 3102.1,
    notes: 'Reproduced on last two starts. Suspect plug fouling or mag timing drift.',
  },
  {
    id: 'SQ-1043',
    tail: 'N812RP',
    component: 'Right Brake',
    summary: 'Soft pedal feel, slight pull right on heavy braking.',
    severity: 'deferred',
    melDeferrable: true,
    opened: '2026-04-26',
    hoursAtOpen: 3088.9,
    deferredUntil: '2026-05-10',
    notes: 'MEL deferral. Pads at 22% — schedule replacement next inspection.',
  },
  {
    id: 'SQ-1044',
    tail: 'N350KA',
    component: 'Cabin Pressurization',
    summary: 'Slow climb to scheduled differential, +12 sec vs nominal.',
    severity: 'deferred',
    melDeferrable: true,
    opened: '2026-04-27',
    hoursAtOpen: 5613.4,
    deferredUntil: '2026-05-15',
    notes: 'Within MEL limits. Outflow valve service due at next phase inspection.',
  },
  {
    id: 'SQ-1045',
    tail: 'N58BS',
    component: 'L Engine — Cyl #4 CHT',
    summary: 'CHT exceeded 420°F twice during climb out of KSEZ.',
    severity: 'open',
    melDeferrable: false,
    opened: '2026-04-28',
    hoursAtOpen: 2486.0,
    notes: 'Recommend cowl flap inspection + climb profile review. Two overtemps logged.',
  },
  {
    id: 'SQ-1046',
    tail: 'N210BS',
    component: 'Main Tires (both)',
    summary: 'Tread at 18% — below replacement threshold.',
    severity: 'grounding',
    melDeferrable: false,
    opened: '2026-04-22',
    hoursAtOpen: 4217.4,
    notes: 'Hard landing logged on prior session (-621 fpm). Inspect strut packings.',
  },
  {
    id: 'SQ-1047',
    tail: 'N210BS',
    component: 'Battery SOH',
    summary: 'State-of-health 44% — slow cranking, two deep-discharge events.',
    severity: 'grounding',
    melDeferrable: false,
    opened: '2026-04-22',
    hoursAtOpen: 4217.4,
    notes: 'Replace before next flight. Concorde RG-35AXC on order.',
  },
  {
    id: 'SQ-1048',
    tail: 'N210BS',
    component: 'Vacuum Pump',
    summary: 'Suction reading 4.2 inHg, below 4.5 minimum.',
    severity: 'grounding',
    melDeferrable: false,
    opened: '2026-04-22',
    hoursAtOpen: 4217.4,
    notes: 'Pump at 612 hours TBO. Replacement scheduled.',
  },
];

window.SIM_STATUS_DEFAULT = {
  simconnect: 'connected',     // connected | connecting | error | offline
  mobiflight: 'connected',
  fsuipc: 'detected',
  aircraftDetected: 'Beechcraft King Air 350',
  bindingProfile: 'BE350.default v1.4',
  tickHz: 4,
  uptime: '02:14:08',
};

window.STATUS_META = {
  airworthy: { label: 'AIRWORTHY',  color: '#7fb069', dot: '#9bd17e' },
  squawks:   { label: 'SQUAWKS',    color: '#d4a24c', dot: '#e8b85a' },
  'mx-due':  { label: 'MX DUE',     color: '#d97757', dot: '#e88a6b' },
  grounded:  { label: 'GROUNDED',   color: '#c25450', dot: '#d96a66' },
};

window.fmtHrs = (h) => h.toFixed(1) + ' h';
window.fmtPct = (n) => Math.round(n * 100) + '%';
window.fmtCycles = (c) => c.toLocaleString();
