// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsfsFailures.Data;

#nullable disable

namespace MsfsFailures.Data.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    partial class FleetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MsfsFailures.Data.Entities.Accelerator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormulaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Accelerators");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Airframe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelRefId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCycles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalHobbsHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelRefId");

                    b.HasIndex("Tail")
                        .IsUnique();

                    b.ToTable("Airframes");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirframeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cycles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastServicedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Wear")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AirframeId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.ComponentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumableKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModelRefId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MtbfHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplaceIntervalCycles")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ReplaceIntervalHours")
                        .HasColumnType("REAL");

                    b.Property<string>("WearCurveJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelRefId");

                    b.ToTable("ComponentTemplates");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Consumable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirframeId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastTopUpAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Level")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AirframeId");

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.FailureMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MelDeferrable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RepairHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimBindingKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SimBindingPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("FailureModes");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.MaintenanceAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirframeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentsTouchedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursAtAction")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirframeId");

                    b.ToTable("MaintenanceActions");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.ModelRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SimMatchRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelRefs");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirframeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HardLandings")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HobbsEnd")
                        .HasColumnType("REAL");

                    b.Property<double>("HobbsStart")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxG")
                        .HasColumnType("REAL");

                    b.Property<string>("OvertempEventsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirframeId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Squawk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirframeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeferredUntil")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FailureModeId")
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursAtOpen")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Opened")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FailureModeId");

                    b.HasIndex("AirframeId", "Status");

                    b.ToTable("Squawks");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.VarBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelRefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelRefId", "LogicalName");

                    b.ToTable("VarBindings");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Airframe", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.ModelRef", "ModelRef")
                        .WithMany()
                        .HasForeignKey("ModelRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelRef");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Component", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.Airframe", "Airframe")
                        .WithMany("Components")
                        .HasForeignKey("AirframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsfsFailures.Data.Entities.ComponentTemplate", "Template")
                        .WithMany("Components")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airframe");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.ComponentTemplate", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.ModelRef", "ModelRef")
                        .WithMany("ComponentTemplates")
                        .HasForeignKey("ModelRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelRef");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Consumable", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.Airframe", "Airframe")
                        .WithMany("Consumables")
                        .HasForeignKey("AirframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airframe");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.FailureMode", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.ComponentTemplate", "Template")
                        .WithMany("FailureModes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.MaintenanceAction", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.Airframe", "Airframe")
                        .WithMany("MaintenanceActions")
                        .HasForeignKey("AirframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airframe");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Session", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.Airframe", "Airframe")
                        .WithMany("Sessions")
                        .HasForeignKey("AirframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airframe");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Squawk", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.Airframe", "Airframe")
                        .WithMany("Squawks")
                        .HasForeignKey("AirframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsfsFailures.Data.Entities.FailureMode", "FailureMode")
                        .WithMany("Squawks")
                        .HasForeignKey("FailureModeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Airframe");

                    b.Navigation("FailureMode");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.VarBinding", b =>
                {
                    b.HasOne("MsfsFailures.Data.Entities.ModelRef", "ModelRef")
                        .WithMany("VarBindings")
                        .HasForeignKey("ModelRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelRef");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.Airframe", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Consumables");

                    b.Navigation("MaintenanceActions");

                    b.Navigation("Sessions");

                    b.Navigation("Squawks");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.ComponentTemplate", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("FailureModes");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.FailureMode", b =>
                {
                    b.Navigation("Squawks");
                });

            modelBuilder.Entity("MsfsFailures.Data.Entities.ModelRef", b =>
                {
                    b.Navigation("ComponentTemplates");

                    b.Navigation("VarBindings");
                });
#pragma warning restore 612, 618
        }
    }
}
