#!/usr/bin/env python3
"""
Generate Files.wxs for WiX v5 from publish/win-x64 directory.
Run from repo root: python3 installer/gen_wxs.py
"""
import os
import uuid
import hashlib

PUBLISH_DIR = "publish/win-x64"
OUTPUT = "installer/MsfsFailures.Installer/Files.wxs"

# Directory -> WiX Directory Id mapping
# Root is INSTALLFOLDER
dir_ids = {}

def dir_id(rel_path):
    """Generate a stable WiX directory Id for a relative path."""
    if rel_path == "":
        return "INSTALLFOLDER"
    # Use a deterministic approach
    safe = rel_path.replace("/", "_").replace("-", "_").replace(".", "_")
    # Ensure valid WiX identifier (must start with letter)
    return "dir_" + safe

def comp_id(rel_path):
    """Generate a stable component Id from file relative path (max 72 chars)."""
    h = hashlib.md5(rel_path.encode()).hexdigest()[:12]
    safe = os.path.basename(rel_path).replace(".", "_").replace("-", "_")
    # Truncate name portion so total stays under 72 chars: "c_" + name + "_" + hash
    max_name = 72 - 2 - 1 - 12  # "c_" + "_" + hash
    safe = safe[:max_name]
    return f"c_{safe}_{h}"

def file_id(rel_path):
    """Generate a stable file Id from relative path (max 72 chars)."""
    h = hashlib.md5(rel_path.encode()).hexdigest()[:12]
    safe = os.path.basename(rel_path).replace(".", "_").replace("-", "_")
    max_name = 72 - 2 - 1 - 12
    safe = safe[:max_name]
    return f"f_{safe}_{h}"

def guid_from_path(rel_path):
    """Generate a stable GUID for a component from its install path."""
    seed = f"MsfsFailures-0.1.0-{rel_path}"
    return str(uuid.uuid5(uuid.NAMESPACE_URL, seed)).upper()

lines = []
lines.append('<?xml version="1.0" encoding="UTF-8"?>')
lines.append('<!-- AUTO-GENERATED by installer/gen_wxs.py — DO NOT EDIT MANUALLY -->')
lines.append('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
lines.append('')
lines.append('  <Fragment>')

# Collect all directories
dirs = set()
all_files = []
for root, subdirs, files in os.walk(PUBLISH_DIR):
    rel_root = os.path.relpath(root, PUBLISH_DIR).replace("\\", "/")
    if rel_root == ".":
        rel_root = ""
    dirs.add(rel_root)
    for f in sorted(files):
        rel_file = os.path.join(rel_root, f).lstrip("/").replace("\\", "/")
        all_files.append((rel_root, rel_file, f))

dirs = sorted(dirs)

# Emit directory structure
lines.append('    <DirectoryRef Id="INSTALLFOLDER">')
# We need to nest directories properly
# Build tree
tree = {}  # parent -> list of children
for d in dirs:
    if d == "":
        continue
    parts = d.split("/")
    parent = "/".join(parts[:-1])
    if parent not in tree:
        tree[parent] = []
    tree[parent].append(d)

def emit_dirs(parent, indent):
    children = tree.get(parent, [])
    for child in sorted(children):
        name = child.split("/")[-1]
        did = dir_id(child)
        lines.append(f'{indent}<Directory Id="{did}" Name="{name}">')
        emit_dirs(child, indent + "  ")
        lines.append(f'{indent}</Directory>')

emit_dirs("", "      ")
lines.append('    </DirectoryRef>')
lines.append('')

# Emit component group with all files
lines.append('    <ComponentGroup Id="AppFiles">')

for (rel_dir, rel_file, fname) in all_files:
    did = dir_id(rel_dir)
    cid = comp_id(rel_file)
    fid = file_id(rel_file)
    guid = guid_from_path(rel_file)
    # Source path relative to where wix build is run (repo root)
    src_path = os.path.join(PUBLISH_DIR, rel_file).replace("/", "\\")

    lines.append(f'      <Component Id="{cid}" Guid="{guid}" Directory="{did}">')
    lines.append(f'        <File Id="{fid}" Source="{src_path}" />')
    lines.append(f'      </Component>')

lines.append('    </ComponentGroup>')
lines.append('  </Fragment>')
lines.append('')
lines.append('</Wix>')

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {OUTPUT} with {len(all_files)} file components across {len(dirs)} directories.")
